### ISSUE TITLE
Magic Link not working

### ISSUE THREAD

**Issue by PatelN123** [steven-tey/dub#119]
Hi,

When I receive the magic link on my own self hosted version, it just redirects me back to the login screen. Please help, thank you.

@steven-tey

**Comment by theabhayprajapati** [comment]
same i am getting the same error with my code.

**Comment by steven-tey** [comment]
Hey! There are probably a bunch of env vars that you need to set up to use this – I'm planning to write up instructions on how to replace email magic link auth with a simpler email/password auth since that will require one less config step (no need to set up an SMTP server). Stay tuned!

In the meantime you can refer to how I'm doing email/password auth in this [simple example](https://github.com/vercel/nextjs-mysql-auth-starter) and try to incorporate that instead of magic link auth.

**Comment by PatelN123** [comment]
Thanks for that.
I do have an SMTP server, would you be able to list he env vars and what they should be?

**Comment by steven-tey** [comment]
Closing this issue for now since we [added Google OAuth](https://dub.sh/changelog/sign-in-with-google) and are deprecating email sign in moving forward!
