### ISSUE TITLE
Add ShareX Support with Custom Links

### ISSUE THREAD

**Issue by niv-dev** [steven-tey/dub#30]
Sorry if this is already possible, but this would genuinely be so helpful

**Comment by steven-tey** [comment]
What do you mean by ShareX support?

**Comment by niv-dev** [comment]
ShareX is a utility that mainly allows for you to share screenshots, but it also has other tools such as a fast url shortener and others. In the URL shortener list, there is support for custom urls, i was asking whether this could be implemented by dub

**Comment by PerchunPak** [comment]
Much easier and better would be to implement a Public API, and then someone will implement an abstraction in ShareX.

Although, developers here can't implement support in ShareX because you need to make it yourself in this tab:
![image](https://user-images.githubusercontent.com/68118654/194690932-64a78b87-a2a0-4259-9faa-1342647e7776.png)

Plus, it is impossible without a Public API.

**Comment by steven-tey** [comment]
Good idea! I'm planning to work on a public API for Dub soon – will update y'all when that's in the works!

**Comment by steven-tey** [comment]
Closing this for now – feel free to follow #73! :)
