### ISSUE TITLE
Black background on the record  when we hover bar graph.

### ISSUE THREAD

**Issue by theabhayprajapati** [steven-tey/dub#42]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/88815641/192505833-957c8ddc-553d-4641-9d98-6a8b4fd9e727.png">

The black background and dark grey colour make it difficult to see the records.

## Steps to reproduce.
1. Open any of your shorten links created with dub.sh.
2. Open analytics for that link.
3. Hover over the bar graph.

**Comment by steven-tey** [comment]
Ahh yes, that's the one piece of dark mode that I missed when I removed dark mode from the application (had to do it because I didn't have enough time to implement it). If you toggle your system mode to light you should see the tooltip go back to white background.

I've put a note and will get this fixed by tonight!

**Comment by steven-tey** [comment]
This has been fixed! 

https://github.com/steven-tey/dub/pull/44

**Comment by theabhayprajapati** [comment]
yeah it's fixed now thanks ![Screenshot_20220928-080510_Chrome.jpg](https://user-images.githubusercontent.com/88815641/192674718-45c32eb4-3fca-41a6-9ec7-ee3f35f682e0.jpg)

**Comment by steven-tey** [comment]
Woohoo! Thanks again for the bug report!
