### ISSUE TITLE
Toggle button for link

### ISSUE THREAD

**Issue by simbafs** [steven-tey/dub#48]
A toggle button, so you can temporally close the link

**Comment by steven-tey** [comment]
I'm not quite sure what you mean, can you elaborate? By "closing the link" do you mean temporarily deactivate it?

**Comment by simbafs** [comment]
Yes, sorry I didn't express it clearly

**Comment by chavda-bhavik** [comment]
Hey, @steven-tey I would like to work on this If it's still relevant.

**Comment by khaosdoctor** [comment]
Building on top of this, a "timer" functionality would be nice, to keep the link active for an X amount of time, since Redis is the base database, we could set TTLs on the links for that (just a guess as I haven't yet looked at the code)

**Comment by steven-tey** [comment]
@khaosdoctor unfortunately that wouldn't work with the [current setup](https://github.com/steven-tey/dub#implementation) since we're using a hash to store links per custom domain.

I am thinking of switching to a more key-value based model though (and move the user-link relation to MySQL, right now we're using Redis sorted sets for that) so we could explore leveraging TTL very soon!

**Comment by steven-tey** [comment]
@khaosdoctor planning to switch over to a key-value-based model (with TTL) this weekend! Will keep all of y'all posted 😄 

Here's the PR if you wanna follow along: https://github.com/steven-tey/dub/pull/78

**Comment by steven-tey** [comment]
Sneak peek of the new UI 👀 🙈 

![CleanShot 2022-10-20 at 13 32 29](https://user-images.githubusercontent.com/28986134/197029781-b3d6465f-54eb-4ad9-81a1-8b2b3af18cda.png)

**Comment by steven-tey** [comment]
Hey guys! This feature is now live (under "Advanced options" > "Expiration Date") 

Feel free to try it out and let me know if there are any bugs 😄 

https://user-images.githubusercontent.com/28986134/197401844-4fd6fc30-e8b6-45eb-9b9f-3941e9452165.mp4
