### ISSUE TITLE
padding and cursor issues on modals and tooltips

### ISSUE THREAD

**Issue by rwlc** [steven-tey/dub#57]
I feel like the text saying "dub.sh/github" could maybe use some margin/padding? It looks extremely weird, and kind of makes the whole spacing uneven.

![image](https://user-images.githubusercontent.com/83243777/193454737-0411c030-95a9-42ac-9e02-b4dc5ba93be0.png)

Furthermore, @steven-tey, on tooltips -- what do you think about making the cursor change to `pointer` on hover? From what I can see, most tooltips implement this behaviour. It could be more user friendly(?). LMK, I'll be happy to work on a PR for this!

**Comment by steven-tey** [comment]
Oh my, this is what happens when you merge your own PRs w/o getting a 2nd pair of eyes to review it 🤣 

Entirely my bad, gonna whip up a quick fix for this now!

Love the idea for having the cursor change to `pointer` on hover! Would love to give you code credits so I'll wait for your PR and merge it! :)

**Comment by steven-tey** [comment]
The padding issue should be fixed with https://github.com/steven-tey/dub/commit/bfc21a1212e7c7b51ef2cf33fbc1064ad18a1b3a

**Comment by rwlc** [comment]
Sure, yeah! I'll code it up as soon as I can. I'll mostly get free in the evening!

**Comment by steven-tey** [comment]
Thank you! Take your time! :)
